name: Deploy dev to self-hosted
concurrency: production

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn
      - name: Test build
        run: yarn test
      - name: Build bot
        run:  yarn build
      - name: Run bot
        env:
          TOKEN: ${{ secrets.TOKEN_DEV }}
        run: pm2 start dist/main.js
