name: Deploy dev to self-hosted
concurrency: production

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn
      - name: Test build
        env:
          PRODUCTION: "true"
          TOKEN: ${{ secrets.TOKEN }}
        run: yarn test
      - name: Build bot
        run:  yarn build
      - name: Stop bot
        run: yarn stop dispress_dev || echo "Bot not running"
      - name: Run bot
        env:
          TOKEN: ${{ secrets.TOKEN_DEV }}
        run: yarn start dispress_dev
