name: Deploy dev to self-hosted
concurrency: production

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: dev
      - name: Install dependencies
        working-directory: ./dev
        run: yarn
      - name: Test build
        working-directory: ./dev
        env:
          PRODUCTION: "true"
          TOKEN: ${{ secrets.TOKEN_DEV }}
        run: yarn test
      - name: Build bot
        working-directory: ./dev
        run:  yarn build
      - name: Restart bot
        working-directory: ./master
        env:
          TOKEN: ${{ secrets.TOKEN }}
          DATABASE_LOCATION: "../dispress.db"
        run: yarn restart dev
