name: Deploy to self-hosted
concurrency: production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    defaults:
      run:
        working-directory: "/home/github/dispress"
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: master
      - name: Install dependencies
        run: yarn
      - name: Test build
        env:
          PRODUCTION: "true"
          TOKEN: ${{ secrets.TOKEN }}
        run: yarn test
      - name: Build bot
        run:  yarn build
      - name: Stop bot
        run: yarn stop dispress || echo "Bot not running"
      - name: Run bot
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: yarn start dispress
