name: Deploy dev to self-hosted
concurrency: production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: master
      - name: Install dependencies
        working-directory: ./master
        run: yarn
      - name: Test build
        working-directory: ./master
        env:
          PRODUCTION: "true"
          TOKEN: ${{ secrets.TOKEN }}
        run: yarn test
      - name: Build bot
        working-directory: ./master
        run:  yarn build
      - name: Stop bot
        working-directory: ./master
        run: yarn stop dispress || echo "Bot not running"
      - name: Run bot
        working-directory: ./master
        env:
          TOKEN: ${{ secrets.TOKEN }}
          DATABASE_LOCATION: "../dispress.db"
        run: yarn start dispress
