name: Deploy to self-hosted
concurrency: production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Test bot
        run: yarn test
      - name: Build bot
        run:  yarn build
      - name: Run bot
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: pm2 start dist/main.js
