name: Test build

on:
  pull_request:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: tests
      - name: Install dependencies
        working-directory: ./tests
        run: yarn
      - name: Build source
        working-directory: ./tests
        run: yarn build
      - name: Run tests
        working-directory: ./tests
        run: yarn test
